import type { Face, Move } from '../moves.js';

import type {
  CanonicalOppositePair,
  MoveTableSpec,
  PruningTableSpec,
  SolverCoordinate,
} from './types.js';

function frozenMove(face: Face, turns: 1 | 2 | 3): Readonly<Move> {
  return Object.freeze({ face, turns });
}

/**
 * Deterministic htm-v1 traversal order. This is deliberately independent of
 * the random-scramble candidate filter.
 */
export const HTM_V1_MOVE_ORDER: readonly Readonly<Move>[] = Object.freeze([
  frozenMove('U', 1),
  frozenMove('U', 3),
  frozenMove('U', 2),
  frozenMove('D', 1),
  frozenMove('D', 3),
  frozenMove('D', 2),
  frozenMove('L', 1),
  frozenMove('L', 3),
  frozenMove('L', 2),
  frozenMove('R', 1),
  frozenMove('R', 3),
  frozenMove('R', 2),
  frozenMove('F', 1),
  frozenMove('F', 3),
  frozenMove('F', 2),
  frozenMove('B', 1),
  frozenMove('B', 3),
  frozenMove('B', 2),
]);

/** Phase-2 entries projected into the stable 18-move htm-v1 order. */
export const PHASE2_TO_HTM_MOVE_INDEX: readonly number[] = Object.freeze([
  0, 1, 2, 3, 4, 5, 8, 11, 14, 17,
]);

/** Phase 2 keeps U/D turns and only half turns on the four side faces. */
export const PHASE2_MOVE_ORDER: readonly Readonly<Move>[] = Object.freeze(
  PHASE2_TO_HTM_MOVE_INDEX.map((index) => HTM_V1_MOVE_ORDER[index]!),
);

/** Inverse lookup in htm-v1 order; half turns are self-inverse. */
export const HTM_V1_INVERSE_MOVE_INDEX: readonly number[] = Object.freeze([
  1, 0, 2, 4, 3, 5, 7, 6, 8, 10, 9, 11, 13, 12, 14, 16, 15, 17,
]);

/** Opposite faces commute; retain only U D, R L, and F B. */
export const CANONICAL_OPPOSITE_PAIRS: readonly CanonicalOppositePair[] =
  Object.freeze([
    Object.freeze({ first: 'U', second: 'D' }),
    Object.freeze({ first: 'R', second: 'L' }),
    Object.freeze({ first: 'F', second: 'B' }),
  ]);

const CANONICAL_OPPOSITE_SUCCESSOR: Readonly<Partial<Record<Face, Face>>> =
  Object.freeze({ U: 'D', R: 'L', F: 'B' });

const OPPOSITE_FACE: Readonly<Record<Face, Face>> = Object.freeze({
  U: 'D',
  D: 'U',
  L: 'R',
  R: 'L',
  F: 'B',
  B: 'F',
});

/**
 * Whether `next` may follow `previous` in one phase's canonical DFS path.
 * A phase boundary passes `null`, intentionally resetting this filter.
 */
export function isCanonicalFaceSuccessor(
  previous: Face | null,
  next: Face,
): boolean {
  if (previous === null) return true;
  if (previous === next) return false;
  if (OPPOSITE_FACE[previous] !== next) return true;
  return CANONICAL_OPPOSITE_SUCCESSOR[previous] === next;
}

/**
 * Which moves may follow which, flattened for the inner loop.
 *
 * {@link isCanonicalFaceSuccessor} compares face letters; doing that per
 * candidate would put string comparison inside the hottest loop in a search.
 * Row 0 is the search root, where anything may come first.
 *
 * Both searches share this because they must share the filter itself: the
 * optimal solver is the oracle the two-phase solver is measured against, and
 * an oracle that enumerates a different set of paths is not measuring the same
 * thing.
 */
export function buildSuccessorMask(order: readonly Readonly<Move>[]): Uint8Array {
  const count = order.length;
  const mask = new Uint8Array((count + 1) * count);
  for (let previous = -1; previous < count; previous += 1) {
    const previousFace: Face | null =
      previous === -1 ? null : (order[previous]!.face as Face);
    for (let next = 0; next < count; next += 1) {
      mask[(previous + 1) * count + next] = isCanonicalFaceSuccessor(
        previousFace,
        order[next]!.face as Face,
      )
        ? 1
        : 0;
    }
  }
  return mask;
}

/** Coordinate cardinalities from DESIGN-SOLVING.md section 2.2. */
export const COORDINATE_SIZES: Readonly<Record<SolverCoordinate, number>> =
  Object.freeze({
    CO: 2_187,
    EO: 2_048,
    UDSlice: 495,
    CP: 40_320,
    UDEdgePerm: 40_320,
    SlicePerm: 24,
  });

function moveTableSpec(
  name: string,
  coordinate: SolverCoordinate,
  moveSet: 'phase1' | 'phase2',
): Readonly<MoveTableSpec> {
  const coordinateCount = COORDINATE_SIZES[coordinate];
  const moveCount =
    moveSet === 'phase1'
      ? HTM_V1_MOVE_ORDER.length
      : PHASE2_MOVE_ORDER.length;
  const entryCount = coordinateCount * moveCount;
  return Object.freeze({
    name,
    coordinate,
    moveSet,
    coordinateCount,
    moveCount,
    entryCount,
    elementEncoding: 'uint16',
    byteLength: entryCount * Uint16Array.BYTES_PER_ELEMENT,
  });
}

/** Six Uint16 coordinate transition tables generated by the M3a table layer. */
export const MOVE_TABLE_SPECS: readonly Readonly<MoveTableSpec>[] = Object.freeze([
  moveTableSpec('co', 'CO', 'phase1'),
  moveTableSpec('eo', 'EO', 'phase1'),
  moveTableSpec('ud-slice', 'UDSlice', 'phase1'),
  moveTableSpec('cp', 'CP', 'phase2'),
  moveTableSpec('ud-edge-perm', 'UDEdgePerm', 'phase2'),
  moveTableSpec('slice-perm', 'SlicePerm', 'phase2'),
]);

function pruningTableSpec(
  name: string,
  phase: 1 | 2,
  firstCoordinate: SolverCoordinate,
  secondCoordinate: SolverCoordinate,
  maximumDepth: number,
): Readonly<PruningTableSpec> {
  const entryCount =
    COORDINATE_SIZES[firstCoordinate] * COORDINATE_SIZES[secondCoordinate];
  return Object.freeze({
    name,
    phase,
    firstCoordinate,
    secondCoordinate,
    entryCount,
    maximumDepth,
    elementEncoding: 'nibble',
    byteLength: Math.ceil(entryCount / 2),
  });
}

/** Four first-version nibble PDBs, including their exhaustive BFS diameters. */
export const PRUNING_TABLE_SPECS: readonly Readonly<PruningTableSpec>[] =
  Object.freeze([
    pruningTableSpec('co-ud-slice', 1, 'CO', 'UDSlice', 9),
    pruningTableSpec('eo-ud-slice', 1, 'EO', 'UDSlice', 9),
    pruningTableSpec('cp-slice-perm', 2, 'CP', 'SlicePerm', 14),
    pruningTableSpec(
      'ud-edge-perm-slice-perm',
      2,
      'UDEdgePerm',
      'SlicePerm',
      12,
    ),
  ]);

export const MOVE_TABLE_BYTE_LENGTH = MOVE_TABLE_SPECS.reduce(
  (total, spec) => total + spec.byteLength,
  0,
);

export const PRUNING_TABLE_BYTE_LENGTH = PRUNING_TABLE_SPECS.reduce(
  (total, spec) => total + spec.byteLength,
  0,
);

export const SOLVER_TABLE_BYTE_LENGTH =
  MOVE_TABLE_BYTE_LENGTH + PRUNING_TABLE_BYTE_LENGTH;

export const TABLE_ARTIFACT_MAGIC = 'RBCT';
export const TABLE_ARTIFACT_FORMAT_VERSION = 1;
export const TABLE_ARTIFACT_BYTE_ORDER = 'LE' as const;
export const TABLE_CHECKSUM_VERSION = 'crc32-v1';
export const NODE_COUNTING_VERSION = 'dfs-expanded-v1';
export const PDB_PACKING_VERSION = 'nibble-v1';
export const COORDINATE_RANKING_VERSION = 'cubie-coordinate-rank-v1';
export const TABLE_GENERATOR_VERSION = 'pair-bfs-v1';

/** Canonical text hashed into SOLVER_FINGERPRINT. Keep byte-for-byte stable. */
export const SOLVER_FINGERPRINT_MANIFEST = [
  'rubcube-kociemba-v1',
  "move-order=htm-v1:U,U',U2,D,D',D2,L,L',L2,R,R',R2,F,F',F2,B,B',B2",
  "phase2-moves=U,U',U2,D,D',D2,L2,R2,F2,B2",
  'canonical=same-face-forbidden;opposites=UD,RL,FB;phase-boundary-reset',
  'phase-depth-limits=12,18',
  `node-counting=${NODE_COUNTING_VERSION}`,
].join('\n');

/** Canonical text hashed into TABLE_FINGERPRINT. Keep byte-for-byte stable. */
export const TABLE_FINGERPRINT_MANIFEST = [
  'rubcube-kociemba-tables-v1',
  'coordinates=CO:2187,EO:2048,UDSlice:495,CP:40320,UDEdgePerm:40320,SlicePerm:24',
  `coordinate-ranking=${COORDINATE_RANKING_VERSION}:CO=base3-msd-co0:6,EO=base2-msd-eo0:10,UDSlice=reverse-combinadic-solved-zero,CP=lexicographic,UDEdgePerm=lexicographic,SlicePerm=lexicographic`,
  "phase1-moves=htm-v1:U,U',U2,D,D',D2,L,L',L2,R,R',R2,F,F',F2,B,B',B2",
  "phase2-moves=U,U',U2,D,D',D2,L2,R2,F2,B2",
  'move-table-encoding=uint16-le;layout=coordinate*move-count+move-index',
  'pdb=CO*UDSlice:1082565@9,EO*UDSlice:1013760@9,CP*SlicePerm:967680@14,UDEdgePerm*SlicePerm:967680@12',
  `pdb-packing=${PDB_PACKING_VERSION};pair-layout=first*second-count+second;low-index=low-nibble;empty=15;odd-tail-high=empty`,
  `generator=${TABLE_GENERATOR_VERSION}`,
  `artifact=${TABLE_ARTIFACT_MAGIC}:${TABLE_ARTIFACT_FORMAT_VERSION}:${TABLE_ARTIFACT_BYTE_ORDER};checksum=${TABLE_CHECKSUM_VERSION}:all-bytes`,
].join('\n');

/** SHA-256 of SOLVER_FINGERPRINT_MANIFEST. */
export const SOLVER_FINGERPRINT =
  'sha256:6bff97476829b96630c3508e9177baef53ef391e0e9f0cff533a50318680b069';

/** SHA-256 of TABLE_FINGERPRINT_MANIFEST. */
export const TABLE_FINGERPRINT =
  'sha256:fc65887c94ef3dbd3d50240e32de0255b92661319acb89775e3acba0c91d8e51';
